### ISSUE TITLE
绘图范例地址失效

### ISSUE THREAD

**Issue by 625781186** [chenluyong/screenshot#1]

**Comment by chenluyong** [comment]
[OEasyScreenshot/src/OE/oescreenshot/oemodelview.cpp](https://github.com/chenluyong/OEasyScreenshot/blob/master/src/OE/oescreenshot/oemodelview.cpp)

**Comment by chenluyong** [comment]
意见被接收，已经修改完毕。

[点击前往此次issue修复的提交标记](https://github.com/chenluyong/OEasyScreenshot/commit/4490539e3eb57bab4f93ebc3559d0641329e2e7f)
