### ISSUE TITLE
'atan2' was not declared in this scope  

### ISSUE THREAD

**Issue by tarzanwill** [chenluyong/screenshot#2]
![image](https://user-images.githubusercontent.com/15139679/61423065-f67e8a80-a940-11e9-8e1f-79ee952fb46b.png)
在选择编译 Release 分支后出现如上 error，请问在哪导入这些呢？（想编译出 exe，但对 C++很陌生 :sweat_smile:

**Comment by chenluyong** [comment]
可以从`pro`中取消这个文件的引用。

因为项目暂时没有使用到`oemodelview`的文件
这个文件原是为画板准备的。

**Comment by tarzanwill** [comment]
了解。
那天后来，我 include 了 QMath，也可编译了。
